language: android
jdk: openjdk8

android:
  components:
    - build-tools-28.0.3

before_install:
    - echo yes | sdkmanager "build-tools;29.0.2"
    - echo yes | sdkmanager "build-tools;28.0.3"

script: TERM=dumb ./gradlew assembleDebug

